# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([ name: 'Star Wars' , { name: 'Lord of the Rings' ])
#   Character.create(name: 'Luke', movie: movies.first)

Item.destroy_all
Movie.destroy_all
User.destroy_all 
Cart.destroy_all
CartsItem.destroy_all

Item.create( name: "'Let Them Eat Chocolate' by Hanksy", description: "Original artwork by Hanksy", price: 700.00, image: "http://i.huffpost.com/gadgets/slideshows/204269/slide_204269_604845_large.jpg?1326291519")
Item.create( name: "'Houston We Have a Problem' by Hanksy", description: "Original artwork by Hanksy", price: 1500.00, image: "http://i.huffpost.com/gadgets/slideshows/204269/slide_204269_604847_large.jpg?1326291519")
Item.create( name: "'Painting Rat' by Hanksy", description: "Original artwork by Hanksy", price: 350.00, image: "http://i.huffpost.com/gadgets/slideshows/204269/slide_204269_604849_large.jpg?1326291519")
Item.create( name: "'Catch Me If You Can' by Hanksy", description: "Original artwork by Hanksy", price: 1000.00, image: "https://muralform.com/wp-content/uploads/2015/03/hanksy-catch-me-if-you-can-crop.jpg")
Item.create( name: "'Laugh Now But One Day We'll Be in Charge' by Hanksy", description: "Original artwork by Hanksy", price: 500.00, image: "http://i.huffpost.com/gadgets/slideshows/204269/slide_204269_604851_large.jpg?1326291519")
Item.create( name: "'Willllsonnnnn!' by Hanksy", description: "Original artwork by Hanksy", price: 1500.00, image: "http://i.huffpost.com/gadgets/slideshows/204269/slide_204269_604852_large.jpg?1326291519")
Item.create( name: "'Street Art is a Money Pit' by Hanksy", description: "Original artwork by Hanksy", price: 900.00, image: "https://www.artnet.com/Images/magazine/features/jen/reverend-jen-hanksy-art-show-1-17-12-6.jpg")
Item.create( name: "'Happy T.Hanksgiving' by Hanksy", description: "Original artwork by Hanksy", price: 350.00, image: "https://i.pinimg.com/originals/c2/37/54/c237544d0a209394fc0fe086adcfcbc0.jpg")
Item.create( name: "'You've Got Male' by Hanksy", description: "Original artwork by Hanksy", price: 1000.00, image: "https://news.artnet.com/app/news-upload/2015/03/hanksy_3.jpeg")
Item.create( name: "'Big' by Hanksy", description: "Original artwork by Hanksy", price: 500.00, image: "https://i0.wp.com/www.lataco.com/wp-content/uploads/hanksy_selfportrait30x30.jpg?fit=2005%2C2017&ssl=1")
Item.create( name: "Tom Hanks Mug", description: "This mug is HANX approved.", price: 16.95, image: "https://i.etsystatic.com/19113428/r/il/fa8744/2119373176/il_fullxfull.2119373176_abur.jpg")
Item.create( name: "'Many T.Hanks' Thank You Card", description: "Mama always said life was like a box of chocolates and you better send a thank you card for that gift! Send this Tom Hanks themed card to your favorite cinephile who deserves your gratitude. This card features Tom Hanks from Cast Away, Forrest Gump, Apollo 13, and Toy Story. Don't forget to check the back for a man's best friend, Wilson!", price: 3.95, image: "https://i.etsystatic.com/7992595/r/il/87a785/917285714/il_fullxfull.917285714_or4c.jpg")
Item.create( name: "Tom Hanks Baby Corn Pin", description: "Have you ever had a really 'Big' secret? Or jumped ecstatically on a trampoline? Or maybe attended a fancy cocktail party and nibbled on some baby corn? Well, our great American treasure Tom Hanks has... Sport this classic and lovable pin of Josh Baskin trying out one of the best hors d'oeuvres ever!", price: 10.00, image: "https://i.etsystatic.com/13668004/d/il/f5c2ad/1280818887/il_340x270.1280818887_516a.jpg?version=1")
Item.create( name: "Tom Hanks Unicorn Pinback Button Magnet", description: "Thomas Jeffrey Hanks is the last unicorn. The most mystical of all creatures. The search is over. It’s him. Thanks to this button, which appeared to me in a forest clearing, us lowly mortals can now own a piece of the magic.", price: 2.45, image: "https://i.etsystatic.com/8471393/r/il/23bd07/649433565/il_794xN.649433565_sbdo.jpg")
Item.create( name: "'Forrest Gump Eats Ice Cream' Tom Hanks Painting Print", description: "I can hear Forrest Gump's voice in my head: Lieutenant Dan, I got you some ice cream.", price: 19.95, image: "https://i.etsystatic.com/5654812/r/il/5fad25/1627406158/il_794xN.1627406158_nl53.jpg")
Item.create( name: "Tom Hanks Vintage Plate", description: "If you don't love Tom Hanks, there may be something wrong with you.... just sayin'. This shallow dish measures approximately 7.5 inches (plate stand not included) across. While we ALL want to eat off Tom Hanks' face, it is not suggested to use this plate for food. Instead why not stare at it adoringly and think 'wowwwww'.", price: 56.00, image: "https://i.etsystatic.com/6500710/r/il/355b24/1841217773/il_794xN.1841217773_m89m.jpg")
Item.create( name: "Tom Hanks Tee Shirt", description: "The man. The myth. The tee shirt.", price: 17.29, image: "https://i.etsystatic.com/13077756/r/il/de500a/1466551729/il_fullxfull.1466551729_l7kk.jpg")
Item.create( name: "Tom Hanks Baby Onesie", description: "There's no crying! This onesie is HANX approved.", price: 17.27, image: "https://ih1.redbubble.net/image.704268040.3025/ra,longsleeve_one_piece,x1250,FFFFFF:97ab1c12de,front-pad,1000x1000,f8f8f8.u20.jpg")
Item.create( name: "Tom Hanks Bath Mat", description: "This bath mat is HANX approved.", price: 21.68, image: "https://ih0.redbubble.net/image.863144617.3025/ur,bathmat_flatlay_context_small,wide_portrait,750x1000.1u20.jpg")
Item.create( name: "Tom Hanks Mini Skirt", description: "Perfect for a night on the town. This mini skirt is HANX approved.", price: 32.05, image: "https://ih0.redbubble.net/image.1062028624.1593/pencil_skirt,x1000,front-c,378,0,871,871-bg,f8f8f8.jpg")
Item.create( name: "Tom Hanks Leggings", description: "These leggings are HANX approved.", price: 42.08, image: "https://ih1.redbubble.net/image.1062028636.1593/ur,leggings_womens_front,square,1000x1000-bg,f8f8f8.jpg")
Item.create( name: "Tom Hanks Laptop Skin", description: "You've got mail. This laptop is HANX approved.", price: 25.46, image: "https://ih1.redbubble.net/image.704268024.3025/pd,x750,macbook_air_13-pad,1000x1000,f8f8f8.u20.jpg")
Item.create( name: "Tom Hanks Floor Pillow", description: "This versatile seating or lounging option will enhance any room.", price: 56.01, image: "https://ih0.redbubble.net/image.704268037.3025/throwpillow,36x36,1000x-bg,f8f8f8-c,0,200,1000,1000.u20.jpg")
Item.create( name: "Tom Hanks iPhone Case/Cover", description: "This iPhone is HANX approved.", price: 21.00, image: "https://ih1.redbubble.net/image.462734307.4934/icr,iphone_11_soft,back,a,x1000-pad,1000x1000,f8f8f8.jpg")
Item.create( name: "Tom Hanks Shower Curtain", description: "Give your bathroom a 'Splash' of pizazz. This shower is HANX approved.", price: 59.53, image: "https://ih1.redbubble.net/image.1062028656.1593/ur,shower_curtain_closed_context,square,1000x1000.1.jpg")
Item.create( name: "Tom Hanks Socks", description: "For when you just feel like running...these socks are HANX approved.", price: 16.83, image: "https://ih1.redbubble.net/image.1062028646.1593/ur,socks_size_comparison_medium,tall_portrait,750x1000-bg,f8f8f8.1.jpg")
Item.create( name: "Tom Hanks Throw Blanket", description: "'Cast away' your day and snuggle up in this coziness. This blanket is HANX approved.", price: 53.21, image: "https://ih0.redbubble.net/image.462734363.4934/ur,blanket_large_bed,square,x1000.1.jpg")# t.string :title


Movie.create(title: "Cast Away", storyline: "A man is marooned on an island after his plane crashes into the ocean. Far away from home, his girlfriend, and any human contact, he engages in a battle of wits with himself as he is tested mentally, physically, and emotionally in order to survive.", trailer: "https://www.youtube.com/embed/qGuOZPwLayY", director: "Robert Zemeckis", description: "A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.", image: "https://m.media-amazon.com/images/M/MV5BN2Y5ZTU4YjctMDRmMC00MTg4LWE1M2MtMjk4MzVmOTE4YjkzXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2000)
Movie.create(title: "Forrest Gump", storyline: "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.", trailer: "https://www.youtube.com/embed/bLvqoHBptjg", director: "Robert Zemeckis", description: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.", image: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR1,0,182,268_AL_.jpg", release_year: 1994)
Movie.create(title: "Saving Private Ryan", storyline: "Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother.", trailer: "https://www.youtube.com/embed/RYID71hYHzg", director: "Steven Spielberg", description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.", image: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR0,0,182,268_AL_.jpg", release_year: 1998)
Movie.create(title: "Philadelphia", storyline: "Fearing it would compromise his career, lawyer Andrew Beckett hides his homosexuality and HIV status at a powerful Philadelphia law firm. But his secret is exposed when a colleague spots the illness's telltale lesions. Fired shortly afterwards, Beckett resolves to sue for discrimination, teaming up with Joe Miller (Denzel Washington), the only lawyer willing to help. In court, they face one of his ex-employers top litigators, Belinda Conine.", trailer: "https://www.youtube.com/embed/cl4B9AU45P4", director: "Jonathan Demme", description: "When a man with HIV is fired by his law firm because of his condition, he hires a homophobic small time lawyer as the only willing advocate for a wrongful dismissal suit.", image: "https://m.media-amazon.com/images/M/MV5BNDE0MWE1ZTMtOWFkMS00YjdiLTkwZTItMDljYjY3MjM0NTk5XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1993)
Movie.create(title: "Joe Versus the Volcano", storyline: "Joe versus the Volcano is a fable which opens with somewhat surrealistic scenes of the dehumanization of Joe Bank's job and work environment (at a company whose product rather literally screws people) with imagery that seems to have been inspired by the classic film Metropolis. Joe is diagnosed with an incurable disease, quits his dehumanizing job, and accepts an offer to briefly 'live like a king, die like a man' - but to fulfill his agreement he must willingly jump into a live volcano on the island of Waponi Woo in order to appease the volcano god. En route to the island, Joe meets a series of interesting characters in NYC and LA, then boards a yacht, captained by Patricia Graynamore. During the voyage Joe and Patricia survive disaster, fall in love, and finally arrive at the island where they face their destiny.", trailer: "https://www.youtube.com/embed/cmQDIne3CLo", director: "John Patrick Shanley", description: "When a hypochondriac learns that he is dying, he accepts an offer to throw himself in a volcano at a tropical island, and along the way there, learns to truly live.", image: "https://m.media-amazon.com/images/M/MV5BYWViOTc3M2ItZDI5Yy00OGMwLWEyYzMtNGY5NDBhMTkyZDkxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1990)
Movie.create(title: "The Terminal", storyline: "Victor Navorski reaches JFK airport from a politically unstable country. Due to collapse of his government, his papers are no longer valid in the airport, and hence he is forced to stay in the airport until the war cools down. He makes the airport his home and develops a friendship with the people who work there until he can leave.", trailer: "https://www.youtube.com/embed/GZjC9dAvWuU", director: "Steven Spielberg", description: "An Eastern European tourist unexpectedly finds himself stranded in JFK airport, and must take up temporary residence there.", image: "https://m.media-amazon.com/images/M/MV5BMTM1MTIwNTMxOF5BMl5BanBnXkFtZTcwNjIxMjQyMw@@._V1_UY268_CR8,0,182,268_AL_.jpg", release_year: 2004)
Movie.create(title: "Splash", storyline: "Allen Bauer is rescued from drowning as a young boy off Cape Cod by a young mermaid. Years later, he returns to the same location, and once again manages to fall into the sea, and is rescued once more by the mermaid (Allen isn't sure what he has seen and what he has imagined). Using maps from a sunken ship, the mermaid decides to search for Allen in New York City, sprouting legs when her tail dries. On finding Allen, they fall in love, but she has a secret, which will no longer be a secret if she gets her legs wet.", trailer: "https://www.youtube.com/embed/uMIsXdoj2vU", director: "Ron Howard", description: "A young man is reunited with a mermaid who saved him from drowning as a boy. He falls in love with her, not knowing who or what she is.", image: "https://m.media-amazon.com/images/M/MV5BZDRmZTQ0MDQtNWRmYS00NDhhLTgzNzUtZGIyYzkwZDMyNTc0L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1984)
Movie.create(title: "The Money Pit", storyline: "Walter Fielding and Anna Crowley have to start looking for a new house- but there's not much they can afford! This soon changes when they meet a lonely old con artist who sells them a beautiful mansion at a ridiculously low price. Only there's a catch. The second they move into the house it falls apart, starting with the stairway collapsing to the bathtub falling through the floor to eventually the chimney falling into the house! Finally, they have to renovate the house before the frame collapses but the renovations also prove to be a disaster.", trailer: "https://www.youtube.com/embed/TLLQquBdU8M", director: "Richard Benjamin", description: "A young couple struggles to repair a hopelessly dilapidated house.", image: "https://m.media-amazon.com/images/M/MV5BNDJmNTZkMDMtOWU5ZS00N2ZlLWIxN2EtZTI4NzBhODc0MmRjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1986)
Movie.create(title: "Turner & Hooch", storyline: "Scott Turner has 3 days left in the local police department before he moves to a bigger city to get some 'real' cases, not just misdemeanors. Then Amos Reed is murdered, and Scott Turner sets himself on the case. The closest thing to a witness in the case is Amos Reed's dog, Hooch, which Scott Turner has to take care of if it's going to avoid being 'put to sleep'.", trailer: "https://www.youtube.com/embed/bqDf22JiTyw", director: "Roger Spottiswoode", description: "A detective must adopt a rambunctious dog in order to help him find a killer.", image: "https://m.media-amazon.com/images/M/MV5BMGYxNjdjMTItMmUwYy00NzNhLTk1NjctZWVkZTMzZTYzNjBmXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1989)
Movie.create(title: "Sleepless in Seattle", storyline: "After his wife Maggie passes away, Sam Baldwin and his 8-year-old son Jonah relocate from Chicago to Seattle to escape the grief associated with Maggie's death. Eighteen months later Sam is still grieving and can't sleep. Although Jonah misses his mother, he wants his father to get a new wife despite Sam having not even contemplated dating again. On Christmas Eve, Sam (on Jonah's initiative) ends up pouring his heart out on a national radio talk show about his magical and perfect marriage to Maggie, and how much he still misses her. Among the many women who hear Sam's story and fall in love with him solely because of it is Annie Reed, a Baltimore-based newspaper writer. Annie's infatuation with Sam's story and by association Sam himself is despite being already engaged. But Annie's relationship with her straight-laced fiancé Walter is unlike her dream love life in the movie An Affair to Remember.", trailer: "https://www.youtube.com/embed/-Lj2U-cmyek", director: "Nora Ephron", description: "A recently widowed man's son calls a radio talk-show in an attempt to find his father a partner.", image: "https://m.media-amazon.com/images/M/MV5BNWY1MDJkZGUtZTE2OS00ODZiLTlmNzQtMDZjNzM2ZjkwM2QxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1993)
Movie.create(title: "Apollo 13", storyline: "Based on the true story of the ill-fated 13th Apollo mission bound for the moon. Astronauts Lovell, Haise and Swigert were scheduled to fly Apollo 14, but are moved up to 13. It's 1970, and The US has already achieved their lunar landing goal, so there's little interest in this 'routine' flight.. until that is, things go very wrong, and prospects of a safe return fade.", trailer: "https://www.youtube.com/embed/KtEIMC58sZo", director: "Ron Howard", description: "NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage putting the lives of the three astronauts on board in jeopardy.", image: "https://m.media-amazon.com/images/M/MV5BNjEzYjJmNzgtNDkwNy00MTQ4LTlmMWMtNzA4YjE2NjI0ZDg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1995)
Movie.create(title: "The Green Mile", storyline: "Death Row guards at a penitentiary, in the 1930's, have a moral dilemma with their job when they discover one of their prisoners, a convicted murderer, has a special gift.", trailer: "https://www.youtube.com/embed/Ki4haFrqSrw", director: "Frank Darabont", description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.", image: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1999)
Movie.create(title: "Toy Story", storyline: "A little boy named Andy loves to be in his room, playing with his toys, especially his doll named 'Woody. But, what do the toys do when Andy is not with them, they come to life. Woody believes that his life (as a toy) is good. However, he must worry about Andy's family moving, and what Woody does not know is about Andy's birthday party. Woody does not realize that Andy's mother gave him an action figure known as Buzz Lightyear, who does not believe that he is a toy, and quickly becomes Andy's new favorite toy. Woody, who is now consumed with jealousy, tries to get rid of Buzz. Then, both Woody and Buzz are now lost. They must find a way to get back to Andy before he moves without them, but they will have to pass through a ruthless toy killer, Sid Phillips.", trailer: "https://www.youtube.com/embed/rNk1Wi8SvNc", director: "John Lasseter", description: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.", image: "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1995)
Movie.create(title: "The Polar Express", storyline: "This is the story of a young hero boy on Christmas Eve who boards on a powerful magical train that's headed to the North Pole and Santa Claus's home. What unfolds is an adventure which follows a doubting boy, who takes an extraordinary train ride to the North Pole; during this ride, he embarks on a journey of self-discovery which shows him that the wonder of life never fades for those who believe.", trailer: "https://www.youtube.com/embed/TQhRqtt-Fpo", director: "Robert Zemeckis", description: "On Christmas Eve, a young boy embarks on a magical adventure to the North Pole on the Polar Express, while learning about friendship, bravery, and the spirit of Christmas.", image: "https://m.media-amazon.com/images/M/MV5BMTM1NTU0NTE4MV5BMl5BanBnXkFtZTcwMTQ0MjEzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2004)
Movie.create(title: "The Da Vinci Code", storyline: "Dan Brown's controversial best-selling novel about a powerful secret that's been kept under wraps for thousands of years comes to the screen in this suspense thriller from Director Ron Howard. The stately silence of Paris' Louvre museum is broken when one of the gallery's leading curators is found dead on the grounds, with strange symbols carved into his body and left around the spot where he died. Hoping to learn the significance of the symbols, police bring in Sophie Neveu (Audrey Tautou), a gifted cryptographer who is also the victim's granddaughter. Needing help, Sophie calls on Robert Langdon (Tom Hanks), a leading symbolized from the United States. As Sophie and Robert dig deeper into the case, they discover the victim's involvement in the Priory of Sion, a secret society whose members have been privy to forbidden knowledge dating back to the birth of Christianity. In their search, Sophie and Robert happen upon evidence that could lead to the final resting place of the Holy Grail, while members of the priory and an underground Catholic society known as Opus Dei give chase, determined to prevent them from sharing their greatest secrets with the world.", trailer: "https://www.youtube.com/embed/lfqHb6INj3w", director: "Ron Howard", description: "A murder inside the Louvre, and clues in Da Vinci paintings, lead to the discovery of a religious mystery protected by a secret society for two thousand years, which could shake the foundations of Christianity.", image: "https://m.media-amazon.com/images/M/MV5BMjIxMjQyMTc3Nl5BMl5BanBnXkFtZTcwMTA1MDUzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2006)
Movie.create(title: "Angels & Demons", storyline: "Following the murder of a physicist, Father Silvano Bentivoglio, a symbolist, Robert Langdon, and a scientist, Vittoria Vetra, are on an adventure involving a secret brotherhood, the Illuminati. Clues lead them all around the Vatican, including the four altars of science, Earth, Air, Fire and Water. An assassin, working for the Illuminati, has captured four cardinals, and murders each, painfully. Robert and Vittoria also are searching for a new very destructive weapon that could kill millions.", trailer: "https://www.youtube.com/embed/GPaAwbveFLg", director: "Ron Howard", description: "Harvard symbologist Robert Langdon works with a nuclear physicist to solve a murder and prevent a terrorist act against the Vatican during one of the significant events within the church.", image: "https://m.media-amazon.com/images/M/MV5BMjEzNzM2MjgxMF5BMl5BanBnXkFtZTcwNTQ1MTM0Mg@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2009)
Movie.create(title: "You've Got Mail", storyline: "The owner of a large bookstore chain starts putting the owner of a small local bookstore out of business. Meanwhile they have been corresponding over the internet without knowing who either of them are. They can't stand each other in person but over the internet they are very attracted. He finds out who she is but she doesn't know. He starts to like her more but she still hates him. He has to fix it.", trailer: "https://www.youtube.com/embed/bjP4s7UUnK8", director: "Nora Ephron", description: "Two business rivals who despise each other in real life unwittingly fall in love over the Internet.", image: "https://m.media-amazon.com/images/M/MV5BZTcxNzgzZjMtYzZiZC00MmE1LTg3MzQtZDAxMTYyZWE4MDNhL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1998)
Movie.create(title: "Captain Phillips", storyline: "Captain Phillips is a multi-layered examination of the 2009 hijacking of the U.S. container ship Maersk Alabama by a crew of Somali pirates. It is - through director Paul Greengrass's distinctive lens - simultaneously a pulse-pounding thriller, and a complex portrait of the myriad effects of globalization. The film focuses on the relationship between the Alabama's commanding officer, Captain Richard Phillips (two time Academy Award®-winner Tom Hanks), and the Somali pirate captain, Muse (Barkhad Abdi), who takes him hostage. Phillips and Muse are set on an unstoppable collision course when Muse and his crew target Phillips' unarmed ship; in the ensuing standoff, 145 miles off the Somali coast, both men will find themselves at the mercy of forces beyond their control.", trailer: "https://www.youtube.com/embed/GEyM01dAxp8", director: "Paul Greengrass", description: "The true story of Captain Richard Phillips and the 2009 hijacking by Somali pirates of the U.S.-flagged MV Maersk Alabama, the first American cargo ship to be hijacked in two hundred years.", image: "https://m.media-amazon.com/images/M/MV5BODhiZWRhMjctNDUyMS00NmUwLTgwYmItMjJhOWNkZWQ3ZTQxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2013)
Movie.create(title: "Sully", storyline: "On Thursday, January 15, 2009, the world witnessed the 'Miracle on the Hudson' when pilot Chesley 'Sully' Sullenberger (Tom Hanks) glided his disabled plane onto the frigid waters of the Hudson River, saving the lives of all one hundred fifty-five aboard. However, even as Sully was being heralded by the public and the media for his unprecedented feat of aviation skill, an investigation was unfolding that threatened to destroy his reputation and his career.", trailer: "https://www.youtube.com/embed/mjKEXxO2KNE", director: "Clint Eastwood", description: "The story of Chesley 'Sully' Sullenberger (Tom Hanks), an American pilot who became a hero after landing his damaged plane on the Hudson River in order to save the flight's passengers and crew.", image: "https://m.media-amazon.com/images/M/MV5BY2NmZDAwM2QtZmFiMS00OTJlLTgxMTItZDMyZmVhYjE1MDY3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2016)
Movie.create(title: "Big", storyline: "Josh Baskin would do anything to be big to hang out with his crush at the carnival. He finds a Zoltar machine, and he wishes to be big. After Zoltar tells him, 'his wish is granted', Josh notices the machine is unplugged. He wakes up the next morning in an adult's body but he still has the same personality. With the help of his best friend, Billy, Josh learns how to act like a grown up. But as he gets a girlfriend and a fun job, he doesn't want to be a kid again. Will Josh stay big or become a 13 year old boy again?", trailer: "https://www.youtube.com/embed/BGDTNhHYJ94", director: "Penny Marshall", description: "After wishing to be made big, a teenage boy wakes the next morning to find himself mysteriously in the body of an adult.", image: "https://m.media-amazon.com/images/M/MV5BMDQ1ODM5MTMtMjAwYi00ZGUxLTliNTMtN2ZhODAwMjVhMTRlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UY268_CR0,0,182,268_AL_.jpg", release_year: 1988)
Movie.create(title: "Bachelor Party", storyline: "Rick Gassko is about to marry Debbie Thompson. Her parents hate him. Her old boyfriend hates him. They all have money and he gets a cut of the crap games on the Catholic school bus that he drives. His friends decide to give him the bachelor party of all bachelor parties in an expensive hotel with booze, adult movies and hookers. As the players catch wind of the elements of the party, each adds a little monkey wrench so that one set of hookers ends up giving demos at the bride's shower, the brides friends end up dressed as hookers in a room with a number of non English speaking Japanese businessmen, and so on, as things get out of hand.", trailer: "https://www.youtube.com/embed/-lxTcw_o6ek", director: "Neal Israel", description: "A soon-to-be-married man's friends throw him the ultimate bachelor party.", image: "https://m.media-amazon.com/images/M/MV5BYjgxOWYxMGQtMTc4MC00MzdmLWI0NTgtYzc1NzFiMGU4MWRjXkEyXkFqcGdeQXVyMzYxMzc3OTM@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1984)
Movie.create(title: "The Man with One Red Shoe", storyline: "Cooper, the deputy director of the CIA, wants to be the director. So, he tries to make it appear that the director is corrupt so that he will resign or be removed. The director appears before a committee and asks for some time to prepare his defense. The director goes home and asks his man Brown to join him. He then shows Brown that Cooper is bugging him. That's when he decides to turn the tables on Cooper by feeding him some false information. And that information is that there's a man, who might be able to clear him of the charges against him, will be arriving at the airport, so he tells Brown to meet him. The Director tells Brown to just pick someone who is arriving at the airport thus making Cooper believe that he is the man who can help the director. Brown picks Richard cause he is wearing mismatched shoes, one of them being red. So Cooper sets up surveillance on Richard and sends his femme fatale, Maddy to come on to him and find out what he knows. While Maddy is playing, Richard actually falls for her.", trailer: "https://www.youtube.com/embed/sKUqdMHoPNQ", director: "Stan Dragoti", description: "A man picked randomly out of a crowd is made the target of CIA survelliance and pursuit.", image: "https://m.media-amazon.com/images/M/MV5BMTJjMWQyODItYjUwNC00ZmVhLWFjOGYtMmI3MTRjYjRjY2U0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR1,0,182,268_AL_.jpg", release_year: 1985)
Movie.create(title: "The 'Burbs", storyline: "In a neighborhood, a family named the Klopeks move into a old house and act very unusual. Everyone nearby is concerned why these people are acting strange and the people have never seen them before. Plus, no one has greeted them for the month they've moved in there. Then 3 people group up to see if they can figure out what is really going on with the Klopeks.", trailer: "https://www.youtube.com/embed/qg7RpL3kTBk", director: "Joe Dante", description: "An overstressed suburbanite and his fellow neighbors are convinced that the new family on the block are part of a murderous Satanic cult.", image: "https://m.media-amazon.com/images/M/MV5BNWE1OGExYzQtYzRjOS00MmJhLWE3OTYtZjkzOTNlMjJlZTQ4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1989)
Movie.create(title: "Dragnet", storyline: "The classic police drama is updated for the 1960s. No-nonsense Sgt. Joe Friday and his partner, Officer Bill Gannon, tackle traditional police cases and face new challenges such as LSD, race riots, and public service TV shows.", trailer: "https://www.youtube.com/embed/tkZTcofj3wU", director: "Tom Mankiewicz", description: "The equally-straight-laced and 'by the book' nephew of Joe Friday must work with his more laid-back partner to solve a mystery.", image: "https://m.media-amazon.com/images/M/MV5BZDIzNTc5YzEtZGFhNS00MDk1LTg2OGUtMWE2NzllMDg1NzJhXkEyXkFqcGdeQXVyMjY3MjUzNDk@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1987)
Movie.create(title: "A League of Their Own", storyline: "Two Sisters, Kit and Dottie, (Lori Petty and Geena Davis) participate in the Women's Baseball Association, along with other girls on the 'Rockford Peaches' with Interesting and drunk manager Jimmy Dugan, (Tom Hanks) and wild girl Mae Mordibeto, (Madonna) they find themselves surrounded with drama and troubles.", trailer: "https://www.youtube.com/embed/tkZTcofj3wU", director: "Penny Marshall", description: "Two sisters join the first female professional baseball league and struggle to help it succeed amidst their own growing rivalry.", image: "https://m.media-amazon.com/images/M/MV5BNjQ1NTQyYjktZDc5My00NDA1LWI1NmItY2ViNjQ0NDk4NmRjXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1992)
Movie.create(title: "That Thing You Do!", storyline: "Recounts a fable of a pop rock band formed a year after the Beatles took America by storm in early 1964. Jazz aficionado Guy Patterson, unhappily toiling in the family appliance store, is recruited into the band the Oneders (later renamed the Wonders) after regular drummer Chad breaks his arm. After Guy injects a four/four rock beat into lead singer Jimmy's ballad, the song's undeniable pop power flings the Wonders into a brief whirlwind of success, telling the tale of many American bands who attempted to grab the brass ring of rock and roll in the wake of the British Invasion.", trailer: "https://www.youtube.com/embed/Vs_h7YdIe_k", director: "Tom Hanks", description: "A local Pennsylvania band scores a one hit wonder in 1964 and rides the star-making machinery as long as they can, with lots of help from its manager.", image: "https://m.media-amazon.com/images/M/MV5BOWVmN2ZhZjgtZGEzMy00NDkxLWI5YWQtYTE2ZTk0YzIyMzc0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1996)
Movie.create(title: "Catch Me If You Can", storyline: "New Rochelle, the 1960s. High schooler Frank Abagnale Jr. idolizes his father, who's in trouble with the IRS. When his parents separate, Frank runs away to Manhattan with $25 in his checking account, vowing to regain dad's losses and get his parents back together. Just a few years later, the FBI tracks him down in France; he's extradited, tried, and jailed for passing more than $4,000,000 in bad checks. Along the way, he's posed as a Pan Am pilot, a pediatrician, and an attorney. And, from nearly the beginning of this life of crime, he's been pursued by a dour FBI agent, Carl Hanratty. What starts as cat and mouse becomes something akin to father and son.", trailer: "https://www.youtube.com/embed/71rDQ7z4eFg", director: "Steven Spielberg", description: "A seasoned FBI agent pursues Frank Abagnale Jr. who, before his 19th birthday, successfully forged millions of dollars' worth of checks while posing as a Pan Am pilot, a doctor, and a legal prosecutor.", image: "https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2002)
Movie.create(title: "The Ladykillers", storyline: "A remake of the 1955 comedy, the story revolves around a Southern professor who puts together a group of thieves to rob a casino. They rent a room in an old woman's house, but soon she discovers the plot and they must kill her, a task that is more difficult than it seems.", trailer: "https://www.youtube.com/embed/BVL6AjybCZ0", director: "Ethan Coen, Joel Coen", description: "An eccentric, if not charming Southern professor and his crew pose as a classical ensemble in order to rob a casino, all under the nose of his unsuspecting but sharp old landlady.", image: "https://m.media-amazon.com/images/M/MV5BMTYwNjUxMTYzM15BMl5BanBnXkFtZTYwNjgwMjY3._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2004)
Movie.create(title: "A Beautiful Day in the Neighborhood", storyline: "Two-time Oscar®-winner Tom Hanks portrays Mister Rogers in A Beautiful Day in the Neighborhood, a timely story of kindness triumphing over cynicism, based on the true story of a real-life friendship between Fred Rogers and journalist Tom Junod. After a jaded magazine writer (Emmy winner Matthew Rhys) is assigned a profile of Fred Rogers, he overcomes his skepticism, learning about empathy, kindness, and decency from America's most beloved neighbor.", trailer: "https://www.youtube.com/embed/-VLEPhfEN2M", director: "Marielle Helle", description: "Based on the true story of a real-life friendship between Fred Rogers and journalist Lloyd Vogel.", image: "https://m.media-amazon.com/images/M/MV5BZWE3ZDYwNmItOWM5ZS00Y2Q4LTlhNmYtODlhY2QxYzA1MDlhXkEyXkFqcGdeQXVyNjA5MDIyMzU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2019)
Movie.create(title: "Cloud Atlas", storyline: "Everything is connected: an 1849 diary of an ocean voyage across the Pacific, letters from a composer to his lover, a thriller about a conspiracy at a nuclear power plant, a farce about a publisher in a nursing home;, a rebellious clone in futuristic Korea, and the tale of a tribe living on post-apocalyptic Hawaii far in the future.", trailer: "https://www.youtube.com/embed/hWnAqFyaQ5s", director: "Tom Tykwer, Lana Wachowski, Lilly Wachowski", description: "An exploration of how the actions of individual lives impact one another in the past, present and future, as one soul is shaped from a killer into a hero, and an act of kindness ripples across centuries to inspire a revolution.", image: "https://m.media-amazon.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2012)
 

User.create(name: "Tom Hanks")

Cart.create(user_id: User.all.sample.id)

CartsItem.create(item_id: Item.all.sample.id, cart_id: Cart.all.sample.id)
CartsItem.create(item_id: Item.all.sample.id, cart_id: Cart.all.sample.id)
CartsItem.create(item_id: Item.all.sample.id, cart_id: Cart.all.sample.id)