# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([ name: 'Star Wars' , { name: 'Lord of the Rings' ])
#   Character.create(name: 'Luke', movie: movies.first)

# t.string :title
# t.string :director
# t.string :description
# t.string :image
# t.integer :release_year

Movie.create(title: "Cast Away", director: "Robert Zemeckis", description: "A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.", image: "https://m.media-amazon.com/images/M/MV5BN2Y5ZTU4YjctMDRmMC00MTg4LWE1M2MtMjk4MzVmOTE4YjkzXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2000)
Movie.create(title: "Forrest Gump", director: "Robert Zemeckis", description: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.", image: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR1,0,182,268_AL_.jpg", release_year: 1994)
Movie.create(title: "Saving Private Ryan", director: "Steven Spielberg", description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.", image: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR0,0,182,268_AL_.jpg", release_year: 1998)
Movie.create(title: "Philadelphia", director: "Jonathan Demme", description: "When a man with HIV is fired by his law firm because of his condition, he hires a homophobic small time lawyer as the only willing advocate for a wrongful dismissal suit.", image: "https://m.media-amazon.com/images/M/MV5BNDE0MWE1ZTMtOWFkMS00YjdiLTkwZTItMDljYjY3MjM0NTk5XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1993)
Movie.create(title: "Joe Versus the Volcano", director: "John Patrick Shanley", description: "When a hypochondriac learns that he is dying, he accepts an offer to throw himself in a volcano at a tropical island, and along the way there, learns to truly live.", image: "https://m.media-amazon.com/images/M/MV5BYWViOTc3M2ItZDI5Yy00OGMwLWEyYzMtNGY5NDBhMTkyZDkxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1990)
Movie.create(title: "The Terminal", director: "Steven Spielberg", description: "An Eastern European tourist unexpectedly finds himself stranded in JFK airport, and must take up temporary residence there.", image: "https://m.media-amazon.com/images/M/MV5BMTM1MTIwNTMxOF5BMl5BanBnXkFtZTcwNjIxMjQyMw@@._V1_UY268_CR8,0,182,268_AL_.jpg", release_year: 2004)
Movie.create(title: "Splash", director: "Ron Howard", description: "A young man is reunited with a mermaid who saved him from drowning as a boy. He falls in love with her, not knowing who or what she is.", image: "https://m.media-amazon.com/images/M/MV5BZDRmZTQ0MDQtNWRmYS00NDhhLTgzNzUtZGIyYzkwZDMyNTc0L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1984)
Movie.create(title: "The Money Pit", director: "Richard Benjamin", description: "A young couple struggles to repair a hopelessly dilapidated house.", image: "https://m.media-amazon.com/images/M/MV5BNDJmNTZkMDMtOWU5ZS00N2ZlLWIxN2EtZTI4NzBhODc0MmRjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1986)
Movie.create(title: "Turner & Hooch", director: "Roger Spottiswoode", description: "A detective must adopt a rambunctious dog in order to help him find a killer.", image: "https://m.media-amazon.com/images/M/MV5BMGYxNjdjMTItMmUwYy00NzNhLTk1NjctZWVkZTMzZTYzNjBmXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1989)
Movie.create(title: "Sleepless in Seattle", director: "Nora Ephron", description: "A recently widowed man's son calls a radio talk-show in an attempt to find his father a partner.", image: "https://m.media-amazon.com/images/M/MV5BNWY1MDJkZGUtZTE2OS00ODZiLTlmNzQtMDZjNzM2ZjkwM2QxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1993)
Movie.create(title: "Apollo 13", director: "Ron Howard", description: "NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage putting the lives of the three astronauts on board in jeopardy.", image: "https://m.media-amazon.com/images/M/MV5BNjEzYjJmNzgtNDkwNy00MTQ4LTlmMWMtNzA4YjE2NjI0ZDg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1995)
Movie.create(title: "The Green Mile", director: "Frank Darabont", description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.", image: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1999)
Movie.create(title: "Toy Story", director: "John Lasseter", description: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.", image: "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1995)
Movie.create(title: "The Polar Express", director: "Robert Zemeckis", description: "On Christmas Eve, a young boy embarks on a magical adventure to the North Pole on the Polar Express, while learning about friendship, bravery, and the spirit of Christmas.", image: "https://m.media-amazon.com/images/M/MV5BMTM1NTU0NTE4MV5BMl5BanBnXkFtZTcwMTQ0MjEzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2004)
Movie.create(title: "The Da Vinci Code", director: "Ron Howard", description: "A murder inside the Louvre, and clues in Da Vinci paintings, lead to the discovery of a religious mystery protected by a secret society for two thousand years, which could shake the foundations of Christianity.", image: "https://m.media-amazon.com/images/M/MV5BMjIxMjQyMTc3Nl5BMl5BanBnXkFtZTcwMTA1MDUzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2006)
Movie.create(title: "Angels & Demons", director: "Ron Howard", description: "Harvard symbologist Robert Langdon works with a nuclear physicist to solve a murder and prevent a terrorist act against the Vatican during one of the significant events within the church.", image: "https://m.media-amazon.com/images/M/MV5BMjEzNzM2MjgxMF5BMl5BanBnXkFtZTcwNTQ1MTM0Mg@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2009)
Movie.create(title: "You've Got Mail", director: "Nora Ephron", description: "Two business rivals who despise each other in real life unwittingly fall in love over the Internet.", image: "https://m.media-amazon.com/images/M/MV5BZTcxNzgzZjMtYzZiZC00MmE1LTg3MzQtZDAxMTYyZWE4MDNhL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1998)
Movie.create(title: "Captain Phillips", director: "Paul Greengrass", description: "The true story of Captain Richard Phillips and the 2009 hijacking by Somali pirates of the U.S.-flagged MV Maersk Alabama, the first American cargo ship to be hijacked in two hundred years.", image: "https://m.media-amazon.com/images/M/MV5BODhiZWRhMjctNDUyMS00NmUwLTgwYmItMjJhOWNkZWQ3ZTQxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2013)
Movie.create(title: "Sully", director: "Clint Eastwood", description: "The story of Chesley 'Sully' Sullenberger (Tom Hanks), an American pilot who became a hero after landing his damaged plane on the Hudson River in order to save the flight's passengers and crew.", image: "https://m.media-amazon.com/images/M/MV5BY2NmZDAwM2QtZmFiMS00OTJlLTgxMTItZDMyZmVhYjE1MDY3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2016)
Movie.create(title: "Big", director: "Penny Marshall", description: "After wishing to be made big, a teenage boy wakes the next morning to find himself mysteriously in the body of an adult.", image: "https://m.media-amazon.com/images/M/MV5BMDQ1ODM5MTMtMjAwYi00ZGUxLTliNTMtN2ZhODAwMjVhMTRlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UY268_CR0,0,182,268_AL_.jpg", release_year: 1988)
Movie.create(title: "Bachelor Party", director: "Neal Israel", description: "A soon-to-be-married man's friends throw him the ultimate bachelor party.", image: "https://m.media-amazon.com/images/M/MV5BYjgxOWYxMGQtMTc4MC00MzdmLWI0NTgtYzc1NzFiMGU4MWRjXkEyXkFqcGdeQXVyMzYxMzc3OTM@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1984)
Movie.create(title: "The Man with One Red Shoe", director: "Stan Dragoti", description: "A man picked randomly out of a crowd is made the target of CIA survelliance and pursuit.", image: "https://m.media-amazon.com/images/M/MV5BMTJjMWQyODItYjUwNC00ZmVhLWFjOGYtMmI3MTRjYjRjY2U0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR1,0,182,268_AL_.jpg", release_year: 1985)
Movie.create(title: "The 'Burbs", director: "Joe Dante", description: "An overstressed suburbanite and his fellow neighbors are convinced that the new family on the block are part of a murderous Satanic cult.", image: "https://m.media-amazon.com/images/M/MV5BNWE1OGExYzQtYzRjOS00MmJhLWE3OTYtZjkzOTNlMjJlZTQ4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1989)
Movie.create(title: "Dragnet", director: "Tom Mankiewicz", description: "The equally-straight-laced and 'by the book' nephew of Joe Friday must work with his more laid-back partner to solve a mystery.", image: "https://m.media-amazon.com/images/M/MV5BZDIzNTc5YzEtZGFhNS00MDk1LTg2OGUtMWE2NzllMDg1NzJhXkEyXkFqcGdeQXVyMjY3MjUzNDk@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1987)
Movie.create(title: "A League of Their Own", director: "Penny Marshall", description: "Two sisters join the first female professional baseball league and struggle to help it succeed amidst their own growing rivalry.", image: "https://m.media-amazon.com/images/M/MV5BNjQ1NTQyYjktZDc5My00NDA1LWI1NmItY2ViNjQ0NDk4NmRjXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1992)
Movie.create(title: "That Thing You Do!", director: "Tom Hanks", description: "A local Pennsylvania band scores a one hit wonder in 1964 and rides the star-making machinery as long as they can, with lots of help from its manager.", image: "https://m.media-amazon.com/images/M/MV5BOWVmN2ZhZjgtZGEzMy00NDkxLWI5YWQtYTE2ZTk0YzIyMzc0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 1996)
Movie.create(title: "Catch Me If You Can", director: "Steven Spielberg", description: "A seasoned FBI agent pursues Frank Abagnale Jr. who, before his 19th birthday, successfully forged millions of dollars' worth of checks while posing as a Pan Am pilot, a doctor, and a legal prosecutor.", image: "https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2002)
Movie.create(title: "The Ladykillers", director: "Ethan Coen, Joel Coen", description: "An eccentric, if not charming Southern professor and his crew pose as a classical ensemble in order to rob a casino, all under the nose of his unsuspecting but sharp old landlady.", image: "https://m.media-amazon.com/images/M/MV5BMTYwNjUxMTYzM15BMl5BanBnXkFtZTYwNjgwMjY3._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2004)
Movie.create(title: "A Beautiful Day in the Neighborhood", director: "Marielle Helle", description: "Based on the true story of a real-life friendship between Fred Rogers and journalist Lloyd Vogel.", image: "https://m.media-amazon.com/images/M/MV5BZWE3ZDYwNmItOWM5ZS00Y2Q4LTlhNmYtODlhY2QxYzA1MDlhXkEyXkFqcGdeQXVyNjA5MDIyMzU@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2019)
Movie.create(title: "Cloud Atlas", director: "Tom Tykwer, Lana Wachowski, Lilly Wachowski", description: "An exploration of how the actions of individual lives impact one another in the past, present and future, as one soul is shaped from a killer into a hero, and an act of kindness ripples across centuries to inspire a revolution.", image: "https://m.media-amazon.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_UX182_CR0,0,182,268_AL_.jpg", release_year: 2012)

# REMEMBER TO GET LINKS TO TRAILERS




